// Navigation config — drives the sidebar menu and header breadcrumb.

import { Calendar } from "lucide-react";

export const NAV=[
  {id:"dashboard",      label:"Dashboard",          icon:"⊞", section:"MAIN"},
  { id: "calendar", label: "My Calendar", icon: "📅" },
  {id:"dispatch",       label:"Dispatch Board",      icon:"🚐"},
  {id:"jobs",           label:"Work Orders",         icon:"🔧"},
  {id:"quotations",     label:"Quotations",          icon:"📄"},
  {id:"leadsCRM",       label:"Leads & CRM",         icon:"🎯"},
  {id:"leads",          label:"Leads",               icon:"📌", sub: true},
  {id:"lead_sources",   label:"Lead Sources",        icon:"📌", sub: true},
  {id:"crm_analytics",  label:"CRM Analytics",       icon:"📊"},
  {id:"contract",      label:"Contracts",           icon:"📝"},
  { id: 'contracts', icon: '📝', label: 'Contracts', sub: true },
{ id: 'contract_settings', icon: '⚙️', label: 'Settings', sub: true },
  {id:"tickets",        label:"Support Tickets",     icon:"🎫"},
  {id:"customer",      label:"Customers",           icon:"👥"},
  {id:"customers",      label:"Customers",           icon:"👥", sub: true},
  {id:"customer_type",  label:"Customer Types",      icon:"👤", sub: true},  
  {id:"amc",            label:"AMC Contracts",       icon:"📋"},
  {id:"invoice",       label:"Invoices",            icon:"💰"},
  {id:"invoices",       label:"Invoices",            icon:"💰", sub: true},
  {id:"create_invoice",       label:"Create Invoices", icon:"💰", sub: true},
  {id:"payments",       label:"Payments",            icon:"💳"},
  {id:"finance",         label:"Finance Overview",    icon:"📊"},
  {id:"pricelist",      label:"Price List",          icon:"🏷"},
  {id:"services",      label:"Services",   icon:"🔔"},
  {id:"reminders",      label:"Service Reminders",   icon:"🔔"},
  {id:"technician",    label:"Technicians",         icon:"👷", section:"TEAM"},
  {id:"technicians",    label:"Technicians",         icon:"👷", sub: true},
  {id:"technician_lookups",    label:"Technicians Lookup",icon:"👷", sub: true},
  {id:"recruitment",    label:"Recruitment",         icon:"🧑‍💼"},
  {id:"attendance",     label:"Attendance",          icon:"📅"},
  {id:"clock",          label:"Clock In / Out",      icon:"⏱"},
  {id:"leave",          label:"Leave Management",    icon:"🌴"},
  {id:"salary_payroll", label:"Salary & Payroll",    icon:"💵"},
  {id:"salary",         label:"Salary",    icon:"💵", sub: true},
  {id:"payroll",         label:"Payroll",    icon:"💵", sub: true},
  {id:"advance_incentive", label:"Extras",    icon:"💵", sub: true},
  {id:"expenses",       label:"Expenses",            icon:"🧾"},
  {id:"performance",    label:"Staff Performance",   icon:"📈"},
  {id:"inventories",      label:"Inventory",           icon:"📦", section:"OPERATIONS"},
  {id:"inventory",      label:"Inventory",           icon:"📦", sub: true},
  {id:"part_requests",  label:"Parts Requests",           icon:"📦", sub: true},
  {id:"purchase",       label:"Purchase Orders",     icon:"🛒"},
  {id:"suppliers",      label:"Suppliers",           icon:"🏭"},
  {id:"assets",         label:"Assets & Vehicles",   icon:"🚗"},
  {id:"warranty",       label:"Warranty Tracker",    icon:"🛡"},
  {id:"gaslog",         label:"Gas / F-Gas Log",     icon:"🧪"},
  {id:"tasks",          label:"Task Manager",        icon:"✅"},
  {id:"kanban",         label:"Kanban Board",        icon:"🗂"},
  {id:"timelog",        label:"Time Tracker",        icon:"⏱"},
  {id:"projects",       label:"Projects",            icon:"🏗"},
  {id:"teamchat",       label:"Team Chat",           icon:"💬"},
  {id:"feedback",       label:"Feedback & Ratings",  icon:"⭐"},
  {id:"notices",        label:"Notice Board",        icon:"📌"},
  {id:"complaints",     label:"Complaints",          icon:"💬"},
  {id:"reports",        label:"Reports",             icon:"📊"},
  {id:"sm_dashboard",   label:"Social Dashboard",    icon:"📱", section:"MARKETING"},
  {id:"sm_posts",       label:"Post Scheduler",      icon:"📅"},
  {id:"sm_campaign",    label:"Campaign Manager",    icon:"🚀"},
  {id:"sm_whatsapp",    label:"WhatsApp Marketing",  icon:"💬"},
  {id:"sm_reviews",     label:"Reviews",             icon:"⭐"},
  { id: "error_codes", label: "Error Codes", icon: "⚠️" },
  {id:"sm_content",     label:"Content Library",     icon:"🖼"},
  {id:"notifications",  label:"Notifications",       icon:"🔔", section:"ADMIN"},
  {id:"client_portal",  label:"Client Portal",       icon:"🌐"},
  {id:"setting",       label:"Settings",            icon:"⚙"},
  {id:"settings",       label:"Settings",            icon:"⚙", sub: true},
  {id:"option_sets",    label:"Option Sets",         icon:"🧩", sub: true},
  {id:"gst_sets",    label:"GST Sets",         icon:"🧩", sub: true},
  {id:"deleted_item" ,label: 'Recently Deleted', icon: '🗑'},
];

export const TITLES = {
  dashboard:"Dashboard",   calendar:"My Calendar", jobs:"Work Orders",          quotations:"Quotations",
  leads:"Leads & CRM",              lead_sources:"Lead Sources",
  customers:"Customers",            customer_type:"Customer Types", 
  amc:"AMC Contracts",              invoices:"Invoices", create_invoice:"Create Invoices",
  technicians:"Technicians",        technician_lookups:"Technicians Lookup" ,attendance:"Attendance",
  clock:"Clock In / Out",           salary:"Salary",    payroll:"Payroll", advance_incentive:"Extras" ,expenses:"Expenses",
  inventory:"Inventory",            purchase:"Purchase Orders",    suppliers:"Suppliers",
  assets:"Assets & Vehicles",       warranty:"Warranty Tracker",
  feedback:"Feedback & Ratings",    notices:"Notice Board",        complaints:"Complaints",
  sm_dashboard:"Social Media Hub",  sm_posts:"Post Scheduler",
  sm_campaign:"Campaign Manager",   sm_whatsapp:"WhatsApp Marketing",
  sm_reviews:"Reviews & Reputation", error_codes:"Error Codes" ,sm_content:"Content Library",
  reports:"Reports & Analytics",    settings:"Settings",           kanban:"Kanban Board",
  option_sets:"Option Sets", gst_sets:"GST sets",
  timelog:"Time Tracker",           projects:"Projects",           teamchat:"Team Chat",
  payments:"Payments",              pricelist:"Price List",        reminders:"Service Reminders", services:"Services",
  leave:"Leave Management",         performance:"Staff Performance",
  gaslog:"Gas / F-Gas Log",         tasks:"Task Manager",          contracts:"Contracts",
  tickets:"Support Tickets",        crm_analytics:"CRM Analytics",
  recruitment:"Recruitment",        dispatch:"Dispatch Board",
  notifications:"Notifications",    client_portal:"Client Portal", logout:"Logout", deleted_item:"Recently Deleted",
  part_requests:"Parts Requests", contract_settings:"Settings", finance:"Finance Overview" 
};