import mongoose from 'mongoose';

// ─── Sub-schemas ───────────────────────────────────────────────────────────────

// A single activity-feed entry — auto-generated by the controller whenever
// something meaningful happens to the task (status change, comment, file
// upload, edit, etc). This is what powers the Trello-style activity feed.
const activitySchema = new mongoose.Schema({
  type: {
    type: String,
    enum: ['created', 'status_change', 'comment', 'attachment_added', 'attachment_removed', 'edited', 'priority_change'],
    required: true,
  },
  actor:   { type: String, default: 'Admin' },   // who did it — swap for req.user.name when auth is wired in
  message: { type: String, required: true },      // human-readable line, e.g. "moved this from To Do to In Progress"
  meta:    { type: mongoose.Schema.Types.Mixed },  // optional extra data (old/new values, attachment id, etc)
  at:      { type: Date, default: Date.now },
}, { _id: true });

// A user comment on the task
const commentSchema = new mongoose.Schema({
  author:  { type: String, default: 'Admin' },
  text:    { type: String, required: true },
  at:      { type: Date, default: Date.now },
  editedAt:{ type: Date },
}, { _id: true });

// An uploaded file (image, video, document) attached to the task
const attachmentSchema = new mongoose.Schema({
  fileName:   { type: String, required: true },   // original filename shown to the user
  storedName: { type: String, required: true },   // actual filename on disk (uuid-based, collision-proof)
  url:        { type: String, required: true },   // public path, e.g. /uploads/tasks/<storedName>
  mimeType:   { type: String, required: true },
  size:       { type: Number, required: true },    // bytes
  kind:       { type: String, enum: ['image', 'video', 'document'], required: true },
  uploadedBy: { type: String, default: 'Admin' },
  uploadedAt: { type: Date, default: Date.now },
}, { _id: true });

// ─── Task schema ────────────────────────────────────────────────────────────────
const taskSchema = new mongoose.Schema({
  taskId:     { type: String, unique: true },
  title:      { type: String, required: true },
  category:   { type: String, required: true },
  assignedTo: { type: String, required: true },
  due:        { type: Date,   required: true },
  priority:   { type: String, enum: ['urgent','high','normal','low'], default: 'normal' },
  status:     { type: String, enum: ['todo','in_progress','done'],    default: 'todo'   },
  notes:      { type: String, default: '' },

  // ── NEW: Trello-style additions ──────────────────────────────────────────
  comments:    { type: [commentSchema],    default: [] },
  attachments: { type: [attachmentSchema], default: [] },
  activity:    { type: [activitySchema],   default: [] },

  isDeleted:  { type: Boolean, default: false },
  deletedAt:  { type: Date },
  deletedBy:  { type: String },
}, { timestamps: true });

taskSchema.pre('save', async function (next) {
  if (!this.taskId) {
    const count  = await mongoose.model('Task').countDocuments();
    this.taskId  = `TSK-${String(count + 1).padStart(3, '0')}`;
  }
  next();
});

export default mongoose.model('Task', taskSchema);