import PartRequest from '../models/PartRequest.js';
import { Inventory } from '../models/index.js';
import Technician from '../models/Technician.js';
import { createCRUD } from './crudHelper.js';
import { adminOnly } from '../middleware/auth.js';
import { approveRequest, rejectRequest, getStats } from '../controllers/partRequestController.js';

// Base CRUD: GET /, GET /deleted, GET /:id, POST /, PUT /:id, PUT /:id/restore,
// DELETE /:id, DELETE /:id/hard — all generated by createCRUD.
//
// POST / is used by BOTH the admin panel (rare) and the technician panel
// (normal case, via a technician-scoped token). beforeCreate resolves the
// calling technician from req.user and snapshots the part's name/unit so the
// request stays legible even if the Inventory item changes later.
const router = createCRUD(PartRequest, {
  searchFields: ['reqId', 'partName', 'notes', 'linkedJob'],
  filterFields: ['status', 'urgent', 'technician'],
  softDelete: true,
  populate: ['part', 'technician', 'decidedBy'],
  defaultSort: { createdAt: -1 },
  beforeCreate: async (body, req) => {
    const tech = await Technician.findOne({ user: req.user._id });
    if (!tech) throw new Error('No technician profile is linked to this account.');

    const inv = await Inventory.findById(body.part);
    if (!inv) throw new Error('Selected part was not found in inventory.');

    return {
      ...body,
      technician: tech._id,
      partName: inv.name,
      unit: inv.unit,
      status: 'pending',
    };
  },
});

// ── Static/segment routes — safe to register after createCRUD because they
//    have an extra path segment beyond a bare "/:id" and therefore never
//    collide with it (same reasoning as PUT /:id/mark-paid in paymentRoutes.js) ──
router.put('/:id/approve', adminOnly, approveRequest);
router.put('/:id/reject',  adminOnly, rejectRequest);
router.get('/stats/summary', getStats);

export default router;