import Payment from '../models/Payment.js';
import { createCRUD } from './crudHelper.js';
import {
  createOrder,
  verifyPayment,
  createPaymentLink,
  markPaid,
  getStats,
} from '../controllers/paymentController.js';

// Base CRUD: GET /, GET /deleted, GET /:id, POST /, PUT /:id, PUT /:id/restore,
// DELETE /:id, DELETE /:id/hard — all generated by createCRUD.
const router = createCRUD(Payment, {
  searchFields: ['paymentId', 'invoice', 'customer', 'method', 'ref'],
  filterFields: ['status', 'method'],
  softDelete: true,
  defaultSort: { createdAt: -1 },
});

// ── Razorpay-specific routes (distinct literal/segment paths, so they don't
//    collide with the /:id routes createCRUD already registered) ───────────
router.post('/create-order',   createOrder);
router.post('/verify',         verifyPayment);
router.post('/payment-link',   createPaymentLink);
router.put('/:id/mark-paid',   markPaid);
router.get('/stats/summary',   getStats);

export default router;